services:
  - type: worker
    name: discord-bot
    env: node
    region: oregon
    buildCommand: npm run render-build
    startCommand: npm run render-start
    disk:
      name: discord-bot-data
      mountPath: /app/data
      sizeGB: 1
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: CLIENT_ID  
        sync: false
      - key: NODE_ENV
        value: production